### ISSUE TITLE
implement this in my HDR compressor app

### ISSUE THREAD

**Issue by HCYANG2000** [chemharuka/PQ_HDR_to_Gain_Map_HDR#1]
Hi I want to implement this into my HDR compressor app, could I do that?
you could try on the app here [HDR Compressor](https://github.com/HCYANG2000/Generate_Apple_HDR_Photos)

**Comment by HCYANG2000** [comment]
Thanks a lot for the insights of your work!

**Comment by chemharuka** [comment]
sure!

> Hi I want to implement this into my HDR compressor app, could I do that? you could try on the app here [HDR Compressor](https://github.com/HCYANG2000/Generate_Apple_HDR_Photos)
