### ISSUE TITLE
How to define color format into 10-bit using this output methods?

### ISSUE THREAD

**Issue by ixuonion** [chemharuka/PQ_HDR_to_Gain_Map_HDR#2]
Is there any chances to adjust the output format into 10-bit to better support HDR?

**Comment by chemharuka** [comment]
There are two functions made by Apple for HEIC image output:

CIContext.writeHEIFRepresentation and CIContext.writeHEIF10Representation

First: 8bit output, support gain map HDR
Second: 10 bit output, support PQ HDR

Apple does not officially provide a function to export 10-bit gain map HDR, but I think the base image can support 10 bits, so it may be possible to write a program to export it yourself.

In fact, for the gain map format, you don’t need to worry about the lack of accuracy of 8-bit photos. The gain map provides additional brightness information and there will be no color discontinuity. But for PQ HDR, 10 bits is necessary.

**Comment by chemharuka** [comment]
Now supports 10-bit base image, but the size is doubled
